---
- hosts: all
  user: vagrant
  sudo: yes

# Partiall taken from https://github.com/azavea/ansible-spark. Thanks, Hector!

  vars:
    spark_version: "1.4.0-bin-hadoop2.6"
    spark_mirror: "http://d3kbcqa49mib13.cloudfront.net"
    spark_usr_dir: "/usr/lib/spark"
    spark_conf_dir: "/etc/spark"

  tasks:
  - name: Install Java
    apt: pkg={{ item }} state=latest update_cache=yes
    with_items:
      - openjdk-7-jre

  - name: Download Spark distribution
    get_url: url="{{ spark_mirror }}/spark-{{ spark_version }}.tgz"
             dest="/usr/local/src/spark-{{ spark_version }}.tgz"

  - name: Ensure Spark configuration directory exists
    file: path="{{ spark_conf_dir }}"
          state=directory

  - name: Extract Spark distribution
    unarchive: src="/usr/local/src/spark-{{ spark_version }}.tgz"
               dest="/usr/lib"
               copy=no
               creates="/usr/lib/spark-{{ spark_version }}"

  - name: Setup Spark distribution symlinks
    file: src="{{ item.src }}"
          dest="{{ item.dest }}"
          state=link
    with_items:
      - { src: "/usr/lib/spark-{{ spark_version }}", dest: "{{ spark_usr_dir }}" }
      - { src: "/usr/lib/spark/conf", dest: "{{ spark_conf_dir }}/conf" }

  - name: Create scripts for running Spark binaries
    template: src="templates/spark-shim.j2"
              dest="/usr/bin/{{ item }}"
              mode=0755
    with_items:
      - spark-class
      - spark-shell
      - spark-sql
      - spark-submit
